on: 
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
  workflow_dispatch:

# cancel older runs of a pull request;
# this will not cancel anything for normal git pushes
concurrency:
  group: cancel-old-pr-runs-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [8, 11, 17]

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os == 'windows-latest' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: coursier/cache-action@v6

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin

      - run: ./mill -i findLatestMill --toFile MILL_DEV_VERSION
        if: matrix.os != 'windows-latest' && github.event_name == 'workflow_dispatch'
      - run: ./mill.bat -i findLatestMill --toFile MILL_DEV_VERSION
        if: matrix.os == 'windows-latest' && github.event_name == 'workflow_dispatch'

      - run: ./mill -i __.publishLocal testRepo
        if: matrix.os != 'windows-latest'
      - run: .\mill.bat -i __.publishLocal testRepo
        if: matrix.os == 'windows-latest'
        shell: cmd

      - run: ./mill -i -k __.testCached
        if: matrix.os != 'windows-latest'
      - run: ./mill.bat -i -k __.testCached
        if: matrix.os == 'windows-latest'
        shell: cmd

  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: coursier/cache-action@v6

      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin

      - run: ./mill -i __.mimaReportBinaryIssues
      - run: ./mill -i __.headerCheck

  publish:
    needs: [build, checks]
    if: github.repository == 'jackcviers/mill-guardrail' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency: publish-{{ github.sha }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: coursier/cache-action@v6

      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin

      - run: ./mill -i findLatestMill --toFile MILL_DEV_VERSION
        if: matrix.os != 'windows-latest' && github.event_name == 'workflow_dispatch'
      - run: ./mill.bat -i findLatestMill --toFile MILL_DEV_VERSION
        if: matrix.os == 'windows-latest' && github.event_name == 'workflow_dispatch'

      - run: ./mill -i __.publishLocal $(pwd)/testRepo
        if: matrix.os != 'windows-latest'
      - run: .\mill.bat -i __.publishLocal %GITHUB_WORKSPACE%/testRepo
        if: matrix.os == 'windows-latest'
        shell: cmd

      - name: Setup GPG secrets for publish
        run: |
          gpg --version
          cat <(echo "${{ secrets.GPG_SECRET_KEY }}") | base64 --decode | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Publish to Maven Central
        run: ./mill -i mill.scalalib.PublishModule/publishAll --publishArtifacts --sonatypeCreds ${{secrets.SONATYPE_USER}}:${{ secrets.SONATYPE_PASSWORD }} --gpgArgs --passphrase=${{ secrets.GPG_SECRET_KEY_PASS}},-u 0x0x6ACFFB7C000D6AA9 --batch,--yes,-a,-b,--pinentry-mode,loopback --readTimeout 600000 --awaitTimeout 600000 --release true --signed true
        if: github.event_name != 'workflow_dispatch'